config/routes.rb
Rails.application.routes.draw do

  root 'animals#index'
  get '/index', to: 'animals#index'

  resources :animals

  get  '/new',    to: 'animals#new'
  post '/add',    to: 'animals#create'
  get  '/delete', to: 'animals#delete' 

end

app/models/animal.rb
class Animal < ApplicationRecord

  validates :name, presence: true
  validates :species, presence: true
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(allowed_params)
    if @animal.save
      flash[:success] = "Animal was added to the index successfully!"
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def delete
    if Animal.delete_all > 0
      flash[:warning] = "All entries were removed successfully"
    end
    redirect_to action: 'index'
  end

  private

    def allowed_params
      params.require(:animal).permit(:name, :species)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title (title)
    if title
      "Heroku pgsql test | #{title}"
    else
      "Heroku pgsql test"
    end
  end

end

app/views/animals/index.html.haml
- provide(:title, "Index")

%h1.mb-4.d-flex.align-items-center.justify-content-between
    List of animals
    = link_to "Remove all", delete_path, class: "btn btn-primary" if @animals.count > 0

%table.table.table-striped
    %thead
        %tr
            %th Name
            %th Species
    %tbody
        - @animals.each do |a|
            %tr
                %td= a.name
                %td= a.species

app/views/animals/new.html.haml
.row
    .col-md-6.offset-md-3
        %h1.mb-4.text-center Add animal to the index
        = form_for @animal, ulr: add_path do |f|
            = render 'shared/error_messages'

            .form-group
                = f.label :name
                = f.text_field :name, class: "form-control", autocomplete: "off"

            .form-group
                = f.label :species
                = f.text_field :species, class: "form-control", autocomplete: "off"

            = f.submit "Add animal", class: "w-100 btn btn-primary"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.bg-dark.navbar-dark.mb-4
    .container
        %button.navbar-toggler{ data: { toggle: "collapse", target: '#navbar' }}
            %span.navbar-toggler-icon
        #navbar.collapse.navbar-collapse
            %ul.navbar-nav
                %li.nav-item
                    = link_to "Index", root_path, class: "nav-link"
                %li.nav-item
                    = link_to "New",   new_path, class: "nav-link"

app/views/layouts/application.html.haml
!!! 5
%html
    %head
        %title= full_title(yield(:title))
        = csrf_meta_tags

        = favicon_link_tag
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
        = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %body
        = render 'layouts/header'
        .container
            - flash.each do |message_type, message|
                = content_tag(:div, message, class: "alert alert-#{message_type}")
            = yield
            = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if @animal.errors.any?
    #error_explanation
        .alert.alert-danger
            = "The form contains %s" % pluralize(@animal.errors.count, "error")
        %ul
            - @animal.errors.full_messages.each do |msg, i|
                %li= msg